version: "3.9"

volumes:
  db:
  bundle:
  # elastic:

services:
  db:
    image: postgres:12.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: bash -c "rm -f spec/dummy/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      # - elasticsearch
    stdin_open: true
    tty: true
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:5.0.6

  # elasticsearch:
  #   image: elasticsearch:7.12.0
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #   volumes:
  #     - elastic:/usr/share/elasticsearch/data
  #   healthcheck:
  #     test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 1m
  #       max-file: '10'
  #   ports:
  #     - 9200:9200

  # sidekiq:
  #   <<: *rails
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   ports: []
